pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '0.9.0'
}

include ':app'
include ':tools:make-keyboard-text'
include ':tools:make-emoji-keys'
include ':country_data'
include ':keyboard-listener'
